version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    # Enable to persist data across container builds
    #volumes:
    #  - ./database/data:/data/db
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./database
    depends_on:
      - mongo
    links:
      - mongo
